export const GET_TASK_REQUEST="GET_TASK_REQUEST"
export const GET_TASK_SUCCESS="GET_TASK_SUCCESS"
export const GET_TASK_FAILURE="GET_TASK_FAILURE"

export const UPDATE_TASK_REQUEST="UPDATE_TASK_REQUEST"
export const UPDATE_TASK_SUCCESS="UPDATE_TASK_SUCCESS"
export const UPDATE_TASK_FAILURE="UPDATE_TASK_FAILURE"

export const ADD_SUBTASK_REQUEST="ADD_SUBTASK_REQUEST"
export const ADD_SUBTASK_SUCCESS="ADD_SUBTASK_SUCCESS"
export const ADD_SUBTASK_FAILURE="ADD_SUBTASK_FAILURE"

export const ADD_TASK_REQUEST="ADD_TASK_REQUEST"
export const ADD_TASK_SUCCESS="ADD_TASK_SUCCESS"
export const ADD_TASK_FAILURE="ADD_TASK_FAILURE"


export const DELETE_SUBTASK_REQUEST="DELETE_SUBTASK_REQUEST"
export const DELETE_SUBTASK_SUCCESS="DELETE_SUBTASK_SUCCESS"
export const DELETE_SUBTASK_FAILURE="DELETE_SUBTASK_FAILURE"


